language: ruby
sudo: false
cache:
  bundler: true
rvm:
  - 2.2.3
  - ruby-head
addons:
  postgresql: '9.4'
  code_climate:
    repo_token: a813ce884be14a158262d4e05906c0b6f4e7f4533c41cdf88bda7da84d88297f
services:
  - elasticsearch
bundler_args: --without development doc
before_script:
  - while read line; do export $line; done < .env.test
  - bundle exec rake --trace db:setup
after_success: |
  if [[ "$TRAVIS_BRANCH" == master ]]; then
      npm install -g raml2html && bundle exec rake raml:publish
  fi
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
env:
  global:
  - secure: We8Glu+3KWdnBa3JnahtotsjYSUjyYPaXrMR6bOR90xln20/VYifecmj37PWIO8hdUj4xZ4uKqNNPx6OQaZtxDT+eofOY0/pLxD/3yHS3WBRV5n8w79jh8xQt6Zg2H1/Ic4KIVqoHyQj9fg//Qde8poFSg6GnMezQLAj+vLH460=  # GH_TOKEN
  - secure: Xj2KE+N9NOwwMa8MwAqpCKB7ujhEwR69YrxlskRDcjcoCqDWtRQPfDbPr1X0Nb3bb5MmS1ouoQt6ACccRuJWNQGg/8jI9yaLu4UIroNyv86q0uduhFW4fG0IEjk4W7+wk6o89Q03XbXpp7tvs6t56Ned1ClZOBhZOGl4jtPgJyY=  # OAUTH_CLIENT_ID
  - secure: dhn9CHHyKIRPYSL0t3qPIcQ2GEI9IhSFAPG/JKy4rL1RIOzlxiFYVz9juaDIjGw8Ab7+Pb+tL0zurE76eN3vqx4d6Gw+rDrTl46mbtyqs6MZYSwFMLqqRb3k2m1Y6WKNoB01GVMB2H7AmB0YMUzhaM4WF3h0XWNPRczw3U2X/eI=  # OAUTH_CLIENT_SECRET
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
