language: ruby
rvm:
  - 2.0.0
  - 2.1.1
addons:
  postgresql: "9.3"
cache: bundler
bundler_args: --without development doc
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database sirius_test' -U postgres
  - bundle exec rake --trace db:load
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
addons:
  code_climate:
    repo_token: a813ce884be14a158262d4e05906c0b6f4e7f4533c41cdf88bda7da84d88297f
